[project]
name = "dbt"
version = "0.1.0"
description = "dbt-core environment for dbt projects"
requires-python = ">=3.12.1,<3.13"
dependencies = [
    "dbt-core>=1.10.4",
    "dbt-postgres>=1.10.0",
]
